language: node_js

node_js:
 - "6" # npm-shrinkwrap.json required in Node 6
 - "8"
 - "10"
 - "lts/*"

branches:
  only:
    - master
    - develop
    - update/dependencies
    - feature/NGSIv2
    - feature/autoRuleName

services:
 - mongodb

addons:
  apt:
    sources:
    - mongodb-3.2-precise
    packages:
    - mongodb-org-server

install:
 - npm install

before_install:
 - npm update -q
 - npm install -g grunt-cli
